;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        paredit-kill
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        typescript-insert-and-autoconvert-to-template
        typescript-insert-and-indent
        undo-tree-visualize
        ))

(setq mc/cmds-to-run-once
      '(
        paredit-forward-delete
        smex
        yaml-electric-backspace
        ))
